In [103]:
import numpy as np
x1 = [0]*10
x1[5-1] = 1
x1 = np.array(x1)
x1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

Q1. Vector manipulation
Create a vector of zeros of size 10 but have the fifth value be 1.

In [9]:
x2 = np.arange(10,49 + 1)
x2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
np.linspace(10,49,40)

array([ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
        21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,
        32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
        43.,  44.,  45.,  46.,  47.,  48.,  49.])

Q2: Vector Range
Create a vector with values ranging from 10 to 49, inclusive.

In [35]:
def reverse(x):
    #Input
    #-----
    #x: 1D array
    assert (len(x.shape) == 1),"Not 1D array!"
    #Output
    #------
    #res: 1D array, with the elements of `x` reversed
    res = x[::-1]
    return res

x3 = reverse(x2)   
x3


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Q3. Reverse a vector

In [44]:
def find_nonzero(x):
    #return the indices of non-zero elements of an array.

    #Input:      x:  array
    #Output:     indices: array of integer indices
    indices = []
    for index, element in enumerate(x):
        if element != 0:
            indices.append(index)
    return np.array(indices)

y4 = [[1,2],[0,0],[4,0]]
y4 = [1,2,0,0,4,0]
x4 = find_nonzero(y4)
x4           

array([0, 1, 4])

In [57]:
def find_nonzero(x):
    #return the indices of non-zero elements of an array.

    #Input:      x:  array
    #Output:     indices: array of integer indices
    indices = np.where(x !=0)
    return np.array(indices).T

y4 = np.array([[1,2],[0,0],[4,0]])
y4 = np.array([1,2,0,0,4,0])
x4 = find_nonzero(y4)
x4

array([[0],
       [1],
       [4]])

Q4. Find indices of non-zero elements

In [64]:
x5 = np.random.normal(0, 1, 3*3*3).reshape(3,3,3)
x5

array([[[ 0.41124546,  0.34130031,  0.02625522],
        [ 0.62913124, -0.59939865,  0.31926137],
        [ 0.92791553,  1.16408003,  1.66604268]],

       [[-0.47055556,  0.2526589 , -1.38135062],
        [ 0.12153645,  0.10290447,  0.8205606 ],
        [ 0.71478549, -0.81098071, -1.79501781]],

       [[ 0.16924708,  0.91922688, -0.04513689],
        [ 2.36698083, -0.05125845,  1.59534369],
        [-0.43280814, -0.14127927, -0.48414364]]])

Q5: Array with random values

In [78]:
x6 = np.random.rand(10,10)
print(x6)
print(x6[1])
print(x6[:,3])
min2r = np.amin(x6[1]) #the minimum value of the 2nd row
max4c = np.amax(x6[:,3]) #the maximum value of the 4th column
max4c

[[ 0.12168248  0.58301032  0.04357814  0.51456236  0.0182301   0.74323183
   0.88912126  0.95963462  0.73126321  0.57100692]
 [ 0.10372023  0.81363423  0.67207827  0.40126134  0.14572112  0.06304275
   0.32646672  0.05364126  0.36509413  0.78896993]
 [ 0.69443822  0.23874163  0.19409939  0.48693184  0.54569087  0.50612451
   0.62739181  0.002815    0.60921259  0.18258687]
 [ 0.97421265  0.3740303   0.04669596  0.06622529  0.53491288  0.13053853
   0.65117385  0.76515515  0.11010479  0.43590811]
 [ 0.10280702  0.85609372  0.49948418  0.05914728  0.83637177  0.16780974
   0.36672592  0.88733827  0.85092989  0.29740505]
 [ 0.47430003  0.57837414  0.83006751  0.01352767  0.29373517  0.72131073
   0.86731863  0.27455019  0.24543862  0.20123856]
 [ 0.62304348  0.74089995  0.71933367  0.84430574  0.363354    0.89084545
   0.3606624   0.47460461  0.02192474  0.25006065]
 [ 0.16754458  0.35244419  0.43211561  0.27697992  0.2981165   0.21136472
   0.55811576  0.81327125  0.19199038  0.198021  ]


0.97504692895212608

Q6. Operations on an array with random values

In [96]:
N = 10
x7 = np.linspace(0, 1, N+2)[1:-1] #Create a vector of size 10 with values ranging from 0 to 1, both excluded.
x7

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

Q7. Vector without end points

In [98]:
x8 = np.random.rand(10)
print(x8)
x8s = np.sort(x8)
print(x8s)

[ 0.05978076  0.62567669  0.70492333  0.67403654  0.50844508  0.28587301
  0.03918704  0.96197842  0.77270155  0.87928675]
[ 0.03918704  0.05978076  0.28587301  0.50844508  0.62567669  0.67403654
  0.70492333  0.77270155  0.87928675  0.96197842]


Q8. Sorted random vector

In [102]:
def is_equal(A, B):
    if A.shape != B.shape:
        return False
    if (A==B).all():
        return True
    else:
        return False

A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
C = is_equal(A,B)
C

True

Q9. Test for array equality

In [51]:
import numpy as np
a = np.random.rand(10,8)
b = np.ones((10,8)).T * np.mean(a,axis=1)
print(a - b.T)

[[ 0.21885856 -0.47338813 -0.44442976  0.02600064  0.31919013  0.39161574
  -0.15947966  0.12163248]
 [ 0.27467836  0.2931826  -0.36545757  0.41519168  0.0018298  -0.11896667
  -0.18570745 -0.31475075]
 [ 0.33364015 -0.04247286  0.45836851 -0.43107179 -0.40648095 -0.25027743
  -0.11039743  0.4486918 ]
 [ 0.18864236 -0.40276386  0.27450857 -0.06628435  0.15024198 -0.01243983
  -0.01714025 -0.11476462]
 [-0.27647021  0.3311292   0.05761967  0.18803856 -0.16724411 -0.44114508
   0.31265364 -0.00458167]
 [ 0.47044491 -0.19547305 -0.05512975  0.29537414  0.01523484 -0.33859711
  -0.25552655  0.06367257]
 [-0.39796017 -0.31604993  0.079991    0.49246793 -0.26611261  0.06043079
   0.40389046 -0.05665748]
 [ 0.28705013 -0.31652496 -0.1288682   0.10404333 -0.3504801  -0.16318404
   0.43693754  0.13102629]
 [-0.27384964 -0.15254121 -0.17257336  0.13368684  0.30693033  0.47406224
  -0.08519684 -0.23051836]
 [-0.04015811 -0.01751634  0.2398057  -0.01226199  0.10642886  0.34839515
  -0.26568591 -0.

Q10. Subtract the row mean from rows of a matrix

In [62]:
a = np.random.rand(5,5,3)
b = np.random.rand(5,5).reshape((5,5,1))
c = np.random.rand(3,5,5)
d = np.random.rand(5,5)
a*b
c*d


array([[[ 0.02895532,  0.55585932,  0.1569364 ,  0.18910663,  0.58476999],
        [ 0.53983825,  0.41148716,  0.34053214,  0.11897921,  0.51802119],
        [ 0.06538216,  0.11716466,  0.05204497,  0.06563985,  0.25264538],
        [ 0.01562856,  0.5722857 ,  0.40091869,  0.33516386,  0.22385672],
        [ 0.14463154,  0.32130248,  0.00511989,  0.56832584,  0.0783725 ]],

       [[ 0.17602284,  0.88634104,  0.15978563,  0.05569052,  0.76267603],
        [ 0.62753193,  0.34312608,  0.28696308,  0.06509515,  0.45877096],
        [ 0.14393625,  0.00694242,  0.10790875,  0.13775036,  0.67042165],
        [ 0.29889587,  0.35952427,  0.8623739 ,  0.06102529,  0.09290275],
        [ 0.08199526,  0.08160364,  0.14552063,  0.67307094,  0.04531234]],

       [[ 0.28043546,  0.10738399,  0.35072224,  0.41258086,  0.3640772 ],
        [ 0.70218916,  0.47883161,  0.17620234,  0.22520477,  0.5233881 ],
        [ 0.14403067,  0.13226057,  0.244183  ,  0.01076624,  0.2190019 ],
        [ 0.10878032,

Q11. Multiply arrays
Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

Q12. Creating a new array

In [69]:
Z = list(range(1,15))
[Z[i:i+4] for i in range(11)]

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10],
 [8, 9, 10, 11],
 [9, 10, 11, 12],
 [10, 11, 12, 13],
 [11, 12, 13, 14]]

Q12. Creating a new array

In [72]:
def cart2polar(xy):
    #radius and angle (unit: radii)
    xyData = np.array(xy).T
    radius = np.sqrt(xyData[0]**2 + xyData[1]**2)
    polar = np.arctan(xyData[1]/xyData[0])
    return np.array([radius, polar]).T

xyTest = [[1, 1], [1, 2]]
print(cart2polar(xyTest))  

[[ 1.41421356  0.78539816]
 [ 2.23606798  1.10714872]]


Q13. Convert from Cartesian to polar coordinates

In [84]:
import time

a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
#%time sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.
#time passed for array operation
t_start = time.time()
sol = a * b
t_stop = time.time()
print('{:6.4f} seconds have passed.'.format(t_stop-t_start))

#time passed for loop operation
t_start = time.time()
sol=[]
for i in range(4):
    for j in range(8):
        for k in range(16):
            for l in range(2):
                sol.append(a[i,j,k,l] * b[i,j,k,l])
sol = np.array(sol)
sol.reshape((4,8,16,2))
t_stop = time.time()

print('{:6.4f} seconds have passed.'.format(t_stop-t_start))

0.0001 seconds have passed.
0.0014 seconds have passed.


Q14. Compute and time for loops and array operations.

In [123]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :].copy() #Change: add .copy() to avoid array alias
    aa /= 4.
    a[:2, :] -= aa
    return a*b
    

a = np.ones((3, 2))
b = np.ones((3,1))*3 #Change: the shape of b has change from (3,) to (3,1), 
                     #for the array broadcast operation Generally, all of the dimensions need to be either the same size, 
                     #or one of the dimension sizes for a particular dimension should be of size 1. 
res = calculate(a, b)
assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

Q15. Fix the code

In [8]:
import numpy as np

data = np.loadtxt('./burl1h2010.txt')
#print(data[:,5:7])

def vector_components(data):
    rad = np.pi/180
    components = []
    for wdir, wspd in data:
        u = wspd * np.cos(wdir*rad)
        v = wspd * np.sin(wdir*rad)
        components.append([u,v])
    return components

vector_components(data[:,5:7])

[[-2.0839751113769922, 2.1580194010159532],
 [-1.9607005260540975, 3.0192140446035265],
 [-2.1211991119655793, 2.5279466622926279],
 [1.4553618446362617, 2.7371375378626732],
 [3.1650951214900656, 3.0564968300195883],
 [1.7542302283364206, 5.7378285357782124],
 [4.9350036656871792, 3.5854900389840858],
 [8.6933324366016151, 2.3293714059226867],
 [8.2668505850695428, 2.3704812600261929],
 [13.724402156082173, -1.4424927930936171],
 [9.3717866084377484, 2.8652427062828205],
 [8.3205634652739882, 2.8649997592229792],
 [9.9756405025982424, -0.69756473744125647],
 [13.300000000000001, 0.0],
 [14.0, 0.0],
 [12.2703397930958, 2.3851124422068102],
 [10.012597271166172, 1.9462517528407568],
 [12.352814256337645, 1.0807312100709612],
 [8.8936342304562306, 2.7190568539214524],
 [11.57174298301396, 0.80917509543185351],
 [10.293725518296688, 0.35946481603576003],
 [11.484239649677599, 0.60186349679385409],
 [8.5790508322344881, 0.5999056741994776],
 [10.186021254496652, -0.53382675367803256],
 [9.

Q16. Calculate components of a vector

In [37]:
import glob
class dataclass:
    def __init__(self,filename):
        self.name = filename
        temp = []
        salt = []
        with open(self.name) as f:
            for line in f:
                #print(line.split())
                spline = line.split()
                if '*END*' in spline:
                    break
            for line in f:
                spline = line.split()
                temp.append(float(spline[2]))
                salt.append(float(spline[5]))
        self.temperature = temp
        self.salinity = salt
    def salt_mean(self):
        return np.mean(self.salinity)
    def temp_max(self):
        return np.max(self.temperature)

def show():

    file_list = glob.glob('./MCH/*.cnv2')
    wind = []
    for file in file_list:
        wind.append(dataclass(file))
    #show wind salt_mean() temp_max()
    for w in wind:
        print(w.salt_mean())
        print(w.temp_max())
show()
        

24.6588294118
22.1201
24.5676
22.1937
30.6813685714
21.6295
32.6763725
21.9669
32.488625
21.3977
35.6063884615
21.0634
26.5899
21.8399
26.6528578947
21.857
33.4783
21.5627
27.1877111111
22.2335
31.675515625
21.4142
34.3534861111
21.9679
34.6244560976
21.8395
34.9058574468
21.8607
30.201615
21.2444
31.693
21.6808
28.0313
21.4318
31.9348727273
21.7691
34.2567882353
21.5411
33.0326324324
21.8166
34.7667209524
22.0266
35.2036481481
21.5861
34.9180395833
21.3882
34.9979017544
22.078
35.779
21.6664
35.6410052632
21.4501
30.7637722222
21.0683
31.139225
21.8542
35.9439346667
21.2521
34.1609301887
21.651
35.1763722222
21.6768
28.4391928571
21.9995
34.8213847458
22.1044
33.4016216216
22.1256
34.7590347518
21.9706
35.4064585366
21.6571
35.1767375
21.3915
22.2224
21.09
36.2943267606
21.7081
28.41893125
22.029
34.9198192982
22.211
31.0882173913
21.7947
33.7901
21.6801
35.3660651163
22.0007
35.5611942857
21.6253
35.207218
21.2677
35.828875
21.6703


Q17. (Grad) Write and use a class

In [195]:
def running_mean(vec,N):
    length = len(vec)
    #truncate near the end
    if N >= 0:
        return [np.mean(vec[i:i+N]) if i < length - N else np.mean(vec[i:]) for i in range(length)]
    else:
        return [np.mean(vec[:i+1]) if i < -N else np.mean(vec[i+N:i]) for i in range(length)]
   
Z = list(range(1,100))
N = -3
print(running_mean(Z,-3))
print(running_mean(Z,3))

[1.0, 1.5, 2.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0]
[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.

Q18. (Grad) Running mean